apiVersion: v1
kind: Service
metadata:
  name: localhost
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 1818
      targetPort: 1818
