apiVersion: v1
kind: Service
metadata:
  name: localhost
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 1818
      targetPort: 1818
