apiVersion: v1
kind: Service
metadata:
  name: localhost
spec:
  type: LoadBalancer
  selector:
    app: prueba
  ports:
    - protocol: TCP
      nodePort: 1818
      port: 1818
      targetPort: 1818
