apiVersion: v1
kind: Service
metadata:
  name: prueba-service
spec:
  type: Loadbalancer
  selector:
    app: prueba
  ports:
    - protocol: TCP
    - nodePort: 8081
    - port: 8080
    - targetPort: 8080
