apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: prueba
  ports:
    - protocol: TCP
      nodePort: 8081
      port: 8080
      targetPort: 8080
