apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 1818
      targetPort: 1818
  type: LoadBalancer
